name: intuitive_bayes
channels:
  - conda-forge
dependencies:
  - bambi=0.11.0
  - black=22.3.0
  - click=8.1.3
  - cloudpickle=2.0.0
  - dill=0.3.4
  - ipykernel=6.9.2
  - ipympl=0.8.
  - isort=5.10.1
  - jupyter=1.0.0
  - jupyterlab=3.4.3
  - jupyter_nbextensions_configurator=0.4.1
  - jupytext=1.13.8
  - matplotlib=3.5.2
  - numpy=1.22.4
  - pandas=1.4.2
  - pip=22.1.2
  - pymc>=4.0.0
  - python=3.10.4
  - python-graphviz=0.20
  - rise=5.7.1
  - scipy=1.8.1
  - seaborn=0.11.2
